[project]
name = "MRArbDcf"
version = "3.0.0"
dependencies = ["numpy", "finufft", "psutil"]

description = "Density Compensation Function Design Tool for Arbirary k-Space Trajectoryies."
keywords = ["MRI", "non-Cartesian", "Reconstruction", "DCF", "Density-Compensation"]
authors = [{name = "Rui", email = "Rui.1002@proton.me"}]

license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"

[project.urls]
Repository = "https://github.com/RyanShanghaitech/MRArbDcf"
Examples = "https://github.com/RyanShanghaitech/MRArbDcf/tree/main/example"
