[project]
name = "MRArbDcf"
version = "3.0.1"
dependencies = ["numpy", "finufft", "psutil"]
requires-python = ">=3.10"

description = "Non-Cartesian MRI Density Compensation Toolbox (MRArbDcf)"
keywords = ["MRI", "non-Cartesian", "Reconstruction", "DCF", "Density-Compensation"]
authors = [{name = "Rui Luo", email = "Rui.1002@proton.me"}]

license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"

[project.urls]
Repository = "https://github.com/RyanShanghaitech/MRArbDcf"
Examples = "https://github.com/RyanShanghaitech/MRArbDcf/tree/main/example"
